name: Run tests

on:
  push:
    branches:
    - '**'

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout this repository
      uses: actions/checkout@v2.4.0
    - name: Install Publicodes
      run: nix-shell -p nodejs --run 'cd publicodes ; npm i publicodes@1.0.0-beta.13'
    - name: Run Publicodes Bats tests
      run: nix-shell --run ./run-publicodes-tests.sh

